"""create_tables

Revision ID: 1c7eb0f4abd6
Revises: 
Create Date: 2024-02-20 16:27:51.220330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7eb0f4abd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Numeric(precision=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('last_currency_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_currency_update')
    op.drop_table('currency')
    # ### end Alembic commands ###
