"""update field rate in Currency

Revision ID: c52200b97add
Revises: 65782d6d73e3
Create Date: 2024-02-21 05:07:20.679657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, MetaData


# revision identifiers, used by Alembic.
revision = 'c52200b97add'
down_revision = '65782d6d73e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'rate',
               existing_type=sa.NUMERIC(precision=100, scale=0),
               type_=sa.Numeric(precision=100, scale=20),
               existing_nullable=True)
    # ### end Alembic commands ###

    meta = MetaData()
    meta.reflect(only=('currency', ), bind=op.get_bind())
    currency_table = Table('currency', meta)

    op.bulk_insert(
        currency_table,
        [
            {"title":"United Arab Emirates Dirham","code":"AED","rate":3.969986},
            {"title":"Afghan Afghani","code":"AFN","rate":79.64504},
            {"title":"Albanian Lek","code":"ALL","rate":103.817464},
            {"title":"Armenian Dram","code":"AMD","rate":438.258597},
            {"title":"Netherlands Antillean Guilder","code":"ANG","rate":1.94559},
            {"title":"Angolan Kwanza","code":"AOA","rate":898.741283},
            {"title":"Argentine Peso","code":"ARS","rate":904.955326},
            {"title":"Australian Dollar","code":"AUD","rate":1.646086},
            {"title":"Aruban Florin","code":"AWG","rate":1.94827},
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'rate',
               existing_type=sa.Numeric(precision=100, scale=20),
               type_=sa.NUMERIC(precision=100, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
